### ISSUE TITLE
Large(r) files do not always download/upload properly.

### ISSUE THREAD

**Issue by clr1107** [HolySheet/HolySheet#8]
When large files are uploaded, _sometimes_ they do not properly get downloaded. I am unsure why this occurs, whether it's the upload or download that's the issue, or how to fix it. Rubba said for the test image I was using: 

> the last 1k bytes being written to/from are the same

This is most likely the issue facing the failure of decompression, sometimes, in https://github.com/HolySheet/HolySheet/commit/d053792e4797a821c4125adbe100f82a3a8365fe

**Comment by RubbaBoy** [comment]
Oh my god this was painful to debug, the problem to this was that Google Sheets would remove `"` if there were two of them in a single line upon uploading as a TSV. I alone have something like 20GB or so of throughput of HolySheet and this has never been a problem, why this has never happened before I have no idea but this was fucking horrible.

**Comment by clr1107** [comment]
I can confirm it is now fixed (phew), and it also fixed the compression issue listed in https://github.com/HolySheet/HolySheet/commit/d053792e4797a821c4125adbe100f82a3a8365fe and mentioned in #5. 

Testing using:
`java -jar holysheet.jar -u image.jpg -c zstd`
`sha1sum image.jpg > image.jpg.sha1 && rm image.jpg`
`java -jar holysheet.jar -d image.jpg`
`sha1sum -c image.jpg.sha1`
yields that it has correctly compressed, uploaded, downloaded, decompressed, and is bit perfect.
